### ISSUE TITLE
Not available on Ubuntu

### ISSUE THREAD

**Issue by Gowee** [everdom/ChromeQQ#3]
It reads "请使用PC打开SmartQQ，或下载手机QQ登录。"
OS:Ubuntu 14.04
Version:Chrome 46.0.2490.71 (64-bit)
And the APP's user-agent is pre-set,I cannot change it by other extension.

**Comment by wbchn** [comment]
#2  里面 @everdom 有提到，最大化后出现二维码，扫码后登陆。

已验证没问题：
OS:Ubuntu 15.04
Version:Chrome 47.0.2526.111 (64-bit)

**Comment by Gowee** [comment]
It works, thx.
